ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=BR
network={
    ssid="XYZ"
    psk=761d24afexxxxa4e5e2d9f9c0defd722f2577ef1006294cf354d
}
network={
    ssid="ABRACADABRA"
    psk=fa45f13ff03xxxxxxxxxafae54b7a912bae855e6dbe95d49e3115b959d
}
network={
    ssid="XYZ3"
    psk=87cd406axxxx4495972e303b33875fdd5a57a002213dd3a3cbb4e02d
}
